from django.urls import path

from companies.views_assessment import (
    AssessmentListView,
    AssessmentCreateView,
    AssessmentDetailView,
    AssessmentOverviewView,
    AssessmentEditView,
    AssessmentDeleteView,
    AssessmentToggleActiveView,
    AssessmentPublishView,
    AssessmentQuestionAddView,
    AssessmentQuestionDeleteView,
    AssessmentReportView,
    AssessmentInboxView,
    AssessmentNotificationConfirmView,
    AssessmentTakeView,
    AssessmentResultView,
)
from accounts.views import (
    AiAssistantView,
    AdminLoginView,
    AdminLogoutView,
    DashboardView,
    DepartmentWorkerRegistryView,
    EmployeeMedicalRecordListView,
    EmployeeMedicalRecordSaveView,
    GuidelinePdfView,
    ProfilePageView,
    ProfileUpdateView,
    DepartmentAdminManagementView,
    DepartmentDeleteView,
    DepartmentEditView,
    EntryGuidelineDeleteView,
    EntryGuidelineEditView,
    EntryGuidelineListView,
    EntryGuidelineSendView,
    GuidelineAcknowledgeView,
    GuidelineInboxView,
    GuidelineStatusView,
    InternalGuidelineAcknowledgeView,
    InternalGuidelinePdfView,
    MandatoryGuidelineAcknowledgeView,
    MandatoryGuidelineDeleteView,
    MandatoryGuidelineEditView,
    MandatoryGuidelineInboxView,
    MandatoryGuidelineListView,
    MandatoryGuidelinePdfView,
    ProfessionGuidelineAcknowledgeView,
    ProfessionGuidelineInboxView,
    ProfessionGuidelinePdfView,
    SectionInternalGuidelineDeleteView,
    SectionInternalGuidelineEditView,
    SectionInternalGuidelineListView,
    SectionInternalGuidelineSendView,
    SectionInternalGuidelineStatusView,
    SectionWorkPracticeDeleteView,
    SectionWorkPracticeAssigneeAcceptView,
    SectionWorkPracticeAssignWorkersView,
    SectionWorkPracticeEditView,
    SectionWorkPracticeFinishView,
    SectionWorkPracticeListView,
    SectionWorkPracticeMessageSendView,
    SectionWorkPracticeMessageReadView,
    WorkerGuidelinesInboxView,
    WorkerEntryGuidelineInboxView,
    LandingPageView,
    OrganizationLeaderRegisterView,
    OrganizationEntryGuidelineOverviewView,
    OrganizationWorkerRegistryView,
    RegisterChoiceView,
    SectionAdminManagementView,
    SectionDetailView,
    SectionDeleteView,
    SectionEditView,
    SectionMemberMessageReadView,
    SectionMemberMessagesView,
    SectionWorkerDeleteView,
    SectionWorkerEditView,
    SectionWorkerManagementView,
    ToggleUserBlockView,
    UserManagementView,
    WorkerHierarchyView,
    WorkerRegisterView,
)

urlpatterns = [
    path('', LandingPageView.as_view(), name='home'),
    path('login/', AdminLoginView.as_view(), name='login'),
    path('logout/', AdminLogoutView.as_view(), name='logout'),
    path('register/', RegisterChoiceView.as_view(), name='register-choice'),
    path('register/leader/', OrganizationLeaderRegisterView.as_view(), name='register-leader'),
    path('register/worker/', WorkerRegisterView.as_view(), name='register-worker'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profil/', ProfilePageView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('pdf/yoriknoma/<int:pk>/', GuidelinePdfView.as_view(), name='guideline-pdf'),
    path('dashboard/ai-assistant/', AiAssistantView.as_view(), name='ai-assistant'),
    path('users/', UserManagementView.as_view(), name='users'),
    path('users/<int:pk>/toggle-block/', ToggleUserBlockView.as_view(), name='toggle-block'),
    # Bilimni baholash (Department Assessment)
    path('bilim-baholash/', AssessmentListView.as_view(), name='assessment-list'),
    path('bilim-baholash/hisobot/', AssessmentOverviewView.as_view(), name='assessment-overview'),
    path('bilim-baholash/yaratish/', AssessmentCreateView.as_view(), name='assessment-create'),
    path('bilim-baholash/<int:pk>/', AssessmentDetailView.as_view(), name='assessment-detail'),
    path('bilim-baholash/<int:pk>/tahrirlash/', AssessmentEditView.as_view(), name='assessment-edit'),
    path('bilim-baholash/<int:pk>/ochirish/', AssessmentDeleteView.as_view(), name='assessment-delete'),
    path('bilim-baholash/<int:pk>/faollashtirish/', AssessmentToggleActiveView.as_view(), name='assessment-toggle'),
    path('bilim-baholash/<int:pk>/joriy/', AssessmentPublishView.as_view(), name='assessment-publish'),
    path('bilim-baholash/<int:pk>/savol/qoshish/', AssessmentQuestionAddView.as_view(), name='assessment-question-add'),
    path('bilim-baholash/<int:pk>/savol/<int:qpk>/ochirish/', AssessmentQuestionDeleteView.as_view(), name='assessment-question-delete'),
    path('bilim-baholash/<int:pk>/hisobot/', AssessmentReportView.as_view(), name='assessment-report'),
    path('bilim-baholash/kirish/', AssessmentInboxView.as_view(), name='assessment-inbox'),
    path('bilim-baholash/xabar/<int:npk>/tasdiqlash/', AssessmentNotificationConfirmView.as_view(), name='assessment-confirm'),
    path('bilim-baholash/ishlash/<int:pk>/', AssessmentTakeView.as_view(), name='assessment-take'),
    path('bilim-baholash/natija/<int:apk>/', AssessmentResultView.as_view(), name='assessment-result'),
    path('department-admins/', DepartmentAdminManagementView.as_view(), name='department-admins'),
    path('tashkilot-ishchilari/', OrganizationWorkerRegistryView.as_view(), name='org-workers'),
    path('tashkilot-ishchilari/<slug:status>/', OrganizationWorkerRegistryView.as_view(), name='org-workers-status'),
    path('tashkilot-kirish-yoriknomalari/', OrganizationEntryGuidelineOverviewView.as_view(), name='org-entry-guidelines'),
    path('tibbiy-malumot/', EmployeeMedicalRecordListView.as_view(), name='medical-records'),
    path('tibbiy-malumot/saqlash/', EmployeeMedicalRecordSaveView.as_view(), name='medical-record-save'),
    path('boshqarma-ishchilari/', DepartmentWorkerRegistryView.as_view(), name='department-workers'),
    path('department-admins/<int:pk>/edit/', DepartmentEditView.as_view(), name='department-edit'),
    path('department-admins/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
    path('section-admins/', SectionAdminManagementView.as_view(), name='section-admins'),
    path('section-admins/<int:pk>/', SectionDetailView.as_view(), name='section-detail'),
    path('section-admins/<int:pk>/edit/', SectionEditView.as_view(), name='section-edit'),
    path('section-admins/<int:pk>/delete/', SectionDeleteView.as_view(), name='section-delete'),
    path('kirish-yoriknomalari/', EntryGuidelineListView.as_view(), name='entry-guidelines'),
    path('kirish-yoriknomalari/<int:pk>/edit/', EntryGuidelineEditView.as_view(), name='entry-guideline-edit'),
    path('kirish-yoriknomalari/<int:pk>/delete/', EntryGuidelineDeleteView.as_view(), name='entry-guideline-delete'),
    path('kirish-yoriknomalari/<int:pk>/send/', EntryGuidelineSendView.as_view(), name='entry-guideline-send'),
    path('yoriknomalar-holati/', GuidelineStatusView.as_view(), name='guideline-status'),
    path('majburiy-yoriknomalar/', MandatoryGuidelineListView.as_view(), name='mandatory-guidelines'),
    path('majburiy-yoriknomalar/<int:pk>/edit/', MandatoryGuidelineEditView.as_view(), name='mandatory-guideline-edit'),
    path('majburiy-yoriknomalar/<int:pk>/delete/', MandatoryGuidelineDeleteView.as_view(), name='mandatory-guideline-delete'),
    path('majburiy-yoriknomalarim/', MandatoryGuidelineInboxView.as_view(), name='mandatory-guidelines-inbox'),
    path('pdf/majburiy-yoriknoma/<int:pk>/', MandatoryGuidelinePdfView.as_view(), name='mandatory-guideline-pdf'),
    path('majburiy-yoriknoma-qabul/<int:pk>/', MandatoryGuidelineAcknowledgeView.as_view(), name='mandatory-guideline-acknowledge'),
    path('kasb-yoriknomam/', ProfessionGuidelineInboxView.as_view(), name='profession-guideline-inbox'),
    path('pdf/kasb-yoriknomam/', ProfessionGuidelinePdfView.as_view(), name='profession-guideline-pdf'),
    path('kasb-yoriknoma-qabul/', ProfessionGuidelineAcknowledgeView.as_view(), name='profession-guideline-acknowledge'),
    path('section-workers/', SectionWorkerManagementView.as_view(), name='section-workers'),
    path('section-workers/<int:pk>/edit/', SectionWorkerEditView.as_view(), name='section-worker-edit'),
    path('section-workers/<int:pk>/delete/', SectionWorkerDeleteView.as_view(), name='section-worker-delete'),
    path('xabarnomalar/', SectionMemberMessagesView.as_view(), name='section-member-messages'),
    path('xabarnomalar/<int:pk>/read/', SectionMemberMessageReadView.as_view(), name='section-member-message-read'),
    path('ichki-yoriknomalar/', SectionInternalGuidelineListView.as_view(), name='internal-guidelines'),
    path('ichki-yoriknomalar/<int:pk>/edit/', SectionInternalGuidelineEditView.as_view(), name='internal-guideline-edit'),
    path('ichki-yoriknomalar/<int:pk>/delete/', SectionInternalGuidelineDeleteView.as_view(), name='internal-guideline-delete'),
    path('ichki-yoriknomalar/<int:pk>/send/', SectionInternalGuidelineSendView.as_view(), name='internal-guideline-send'),
    path('ichki-yoriknomalar-holati/', SectionInternalGuidelineStatusView.as_view(), name='internal-guideline-status'),
    path('ish-amaliyotlari/', SectionWorkPracticeListView.as_view(), name='work-practices'),
    path('ish-amaliyotlari/<int:pk>/edit/', SectionWorkPracticeEditView.as_view(), name='work-practice-edit'),
    path('ish-amaliyotlari/<int:pk>/assign-workers/', SectionWorkPracticeAssignWorkersView.as_view(), name='work-practice-assign-workers'),
    path('ish-amaliyotlari/biriktirma/<int:pk>/qabul/', SectionWorkPracticeAssigneeAcceptView.as_view(), name='work-practice-assignee-accept'),
    path('ish-amaliyotlari/<int:pk>/finish/', SectionWorkPracticeFinishView.as_view(), name='work-practice-finish'),
    path('ish-amaliyotlari/<int:pk>/send-message/', SectionWorkPracticeMessageSendView.as_view(), name='work-practice-send-message'),
    path('ish-amaliyoti-xabar/<int:pk>/read/', SectionWorkPracticeMessageReadView.as_view(), name='work-practice-message-read'),
    path('ish-amaliyotlari/<int:pk>/delete/', SectionWorkPracticeDeleteView.as_view(), name='work-practice-delete'),
    path('pdf/ichki-yoriknoma/<int:pk>/', InternalGuidelinePdfView.as_view(), name='internal-guideline-pdf'),
    path('ichki-yoriknomalar-qabul/<int:pk>/', InternalGuidelineAcknowledgeView.as_view(), name='internal-guideline-acknowledge'),
    path('xabarlarim/', WorkerGuidelinesInboxView.as_view(), name='worker-messages-inbox'),
    path('kirish-yoriknomam/', WorkerEntryGuidelineInboxView.as_view(), name='worker-entry-guidelines'),
    path('yo-riqnomalarim/', WorkerGuidelinesInboxView.as_view(), name='worker-guidelines-inbox'),
    path('xabarnomalarim/', GuidelineInboxView.as_view(), name='notifications-inbox'),
    path('mening-yoriknomalar/', GuidelineInboxView.as_view(), name='guideline-inbox'),
    path('yoriknomalar-qabul/<int:pk>/', GuidelineAcknowledgeView.as_view(), name='guideline-acknowledge'),
    path('hierarchy/', WorkerHierarchyView.as_view(), name='worker-hierarchy'),
    path('hierarchy/', WorkerHierarchyView.as_view(), name='hierarchy'),
]
