from django.urls import path

from accounts.views import (
    AiAssistantView,
    AdminLoginView,
    AdminLogoutView,
    DashboardView,
    GuidelinePdfView,
    ProfilePageView,
    ProfileUpdateView,
    DepartmentAdminManagementView,
    DepartmentDeleteView,
    DepartmentEditView,
    EntryGuidelineDeleteView,
    EntryGuidelineEditView,
    EntryGuidelineListView,
    EntryGuidelineSendView,
    GuidelineAcknowledgeView,
    GuidelineInboxView,
    GuidelineStatusView,
    InternalGuidelineAcknowledgeView,
    InternalGuidelinePdfView,
    SectionInternalGuidelineDeleteView,
    SectionInternalGuidelineEditView,
    SectionInternalGuidelineListView,
    SectionInternalGuidelineSendView,
    SectionInternalGuidelineStatusView,
    SectionWorkPracticeDeleteView,
    SectionWorkPracticeEditView,
    SectionWorkPracticeListView,
    WorkerGuidelinesInboxView,
    LandingPageView,
    OrganizationLeaderRegisterView,
    RegisterChoiceView,
    SectionAdminManagementView,
    SectionDeleteView,
    SectionEditView,
    SectionMemberMessageReadView,
    SectionMemberMessagesView,
    SectionWorkerDeleteView,
    SectionWorkerEditView,
    SectionWorkerManagementView,
    ToggleUserBlockView,
    UserManagementView,
    WorkerHierarchyView,
    WorkerRegisterView,
)

urlpatterns = [
    path('', LandingPageView.as_view(), name='home'),
    path('login/', AdminLoginView.as_view(), name='login'),
    path('logout/', AdminLogoutView.as_view(), name='logout'),
    path('register/', RegisterChoiceView.as_view(), name='register-choice'),
    path('register/leader/', OrganizationLeaderRegisterView.as_view(), name='register-leader'),
    path('register/worker/', WorkerRegisterView.as_view(), name='register-worker'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profil/', ProfilePageView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('pdf/yoriknoma/<int:pk>/', GuidelinePdfView.as_view(), name='guideline-pdf'),
    path('dashboard/ai-assistant/', AiAssistantView.as_view(), name='ai-assistant'),
    path('users/', UserManagementView.as_view(), name='users'),
    path('users/<int:pk>/toggle-block/', ToggleUserBlockView.as_view(), name='toggle-block'),
    path('department-admins/', DepartmentAdminManagementView.as_view(), name='department-admins'),
    path('department-admins/<int:pk>/edit/', DepartmentEditView.as_view(), name='department-edit'),
    path('department-admins/<int:pk>/delete/', DepartmentDeleteView.as_view(), name='department-delete'),
    path('section-admins/', SectionAdminManagementView.as_view(), name='section-admins'),
    path('section-admins/<int:pk>/edit/', SectionEditView.as_view(), name='section-edit'),
    path('section-admins/<int:pk>/delete/', SectionDeleteView.as_view(), name='section-delete'),
    path('kirish-yoriknomalari/', EntryGuidelineListView.as_view(), name='entry-guidelines'),
    path('kirish-yoriknomalari/<int:pk>/edit/', EntryGuidelineEditView.as_view(), name='entry-guideline-edit'),
    path('kirish-yoriknomalari/<int:pk>/delete/', EntryGuidelineDeleteView.as_view(), name='entry-guideline-delete'),
    path('kirish-yoriknomalari/<int:pk>/send/', EntryGuidelineSendView.as_view(), name='entry-guideline-send'),
    path('yoriknomalar-holati/', GuidelineStatusView.as_view(), name='guideline-status'),
    path('section-workers/', SectionWorkerManagementView.as_view(), name='section-workers'),
    path('section-workers/<int:pk>/edit/', SectionWorkerEditView.as_view(), name='section-worker-edit'),
    path('section-workers/<int:pk>/delete/', SectionWorkerDeleteView.as_view(), name='section-worker-delete'),
    path('xabarnomalar/', SectionMemberMessagesView.as_view(), name='section-member-messages'),
    path('xabarnomalar/<int:pk>/read/', SectionMemberMessageReadView.as_view(), name='section-member-message-read'),
    path('ichki-yoriknomalar/', SectionInternalGuidelineListView.as_view(), name='internal-guidelines'),
    path('ichki-yoriknomalar/<int:pk>/edit/', SectionInternalGuidelineEditView.as_view(), name='internal-guideline-edit'),
    path('ichki-yoriknomalar/<int:pk>/delete/', SectionInternalGuidelineDeleteView.as_view(), name='internal-guideline-delete'),
    path('ichki-yoriknomalar/<int:pk>/send/', SectionInternalGuidelineSendView.as_view(), name='internal-guideline-send'),
    path('ichki-yoriknomalar-holati/', SectionInternalGuidelineStatusView.as_view(), name='internal-guideline-status'),
    path('ish-amaliyotlari/', SectionWorkPracticeListView.as_view(), name='work-practices'),
    path('ish-amaliyotlari/<int:pk>/edit/', SectionWorkPracticeEditView.as_view(), name='work-practice-edit'),
    path('ish-amaliyotlari/<int:pk>/delete/', SectionWorkPracticeDeleteView.as_view(), name='work-practice-delete'),
    path('pdf/ichki-yoriknoma/<int:pk>/', InternalGuidelinePdfView.as_view(), name='internal-guideline-pdf'),
    path('ichki-yoriknomalar-qabul/<int:pk>/', InternalGuidelineAcknowledgeView.as_view(), name='internal-guideline-acknowledge'),
    path('xabarlarim/', WorkerGuidelinesInboxView.as_view(), name='worker-messages-inbox'),
    path('yo-riqnomalarim/', WorkerGuidelinesInboxView.as_view(), name='worker-guidelines-inbox'),
    path('xabarnomalarim/', GuidelineInboxView.as_view(), name='notifications-inbox'),
    path('mening-yoriknomalar/', GuidelineInboxView.as_view(), name='guideline-inbox'),
    path('yoriknomalar-qabul/<int:pk>/', GuidelineAcknowledgeView.as_view(), name='guideline-acknowledge'),
    path('hierarchy/', WorkerHierarchyView.as_view(), name='worker-hierarchy'),
    path('hierarchy/', WorkerHierarchyView.as_view(), name='hierarchy'),
]
