# Generated by Django 4.2 on 2026-06-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_stored_media_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoredMediaFile',
        ),
    ]
