# Generated by Django 4.2 on 2026-08-04 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPEType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='IHV turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IHV Turi',
                'verbose_name_plural': 'IHV Turlari',
                'db_table': 'ppe_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PPEIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Berilgan sana')),
                ('expiration_date', models.DateField(verbose_name='Amal qilish muddati')),
                ('condition', models.CharField(choices=[('alo', "A'lo"), ('yaxshi', 'Yaxshi'), ('qoniqarli', 'Qoniqarli'), ('yaroqsiz', 'Yaroqsiz')], max_length=20, verbose_name='Holati')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_issues', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_ppes', to=settings.AUTH_USER_MODEL, verbose_name='Beruvchi')),
                ('ppe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ppe.ppetype', verbose_name='IHV Turi')),
            ],
            options={
                'verbose_name': 'IHV Berish',
                'verbose_name_plural': 'IHV Berilganlar',
                'db_table': 'ppe_issue',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
