# Generated by Django 4.2 on 2026-08-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppeissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan sana'),
        ),
    ]
