# Generated by Django 4.2 on 2026-08-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_is_blocked_by_violations'),
        ('ppe', '0002_ppeissue_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppetype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppe_types', to='accounts.userprofile', verbose_name='Tashkilot'),
        ),
    ]
