# Generated by Django 4.2 on 2026-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super admin'), ('organization_leader', 'Tashkilot rahbari'), ('department_admin', 'Boshqarma admini'), ('section_admin', 'Bo‘lim admini'), ('worker', 'Xodim')], max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('is_new_registration', models.BooleanField(default=False)),
                ('practice_qualified', models.BooleanField(default=False, verbose_name="Amaliyotdan o'tgan (ishlashga yaroqli)")),
                ('assessment_qualified', models.BooleanField(blank=True, default=None, null=True, verbose_name="Bilim baholashdan o'tgan (None=sinalmagan, True=o'tdi, False=o'tmadi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'foydalanuvchi',
                'ordering': ['-created_at'],
            },
        ),
    ]
