# Generated by Django 4.2 on 2026-05-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_department_section'),
        ('accounts', '0003_create_default_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='companies.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='companies.section'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('organization_leader', 'Tashkilot rahbari'), ('department_admin', 'Boshqarma admini'), ('section_admin', 'Bo‘lim admini'), ('worker', 'Ishchi')], max_length=32),
        ),
    ]
