# Generated by Django 4.2 on 2026-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_region_userprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_blocked_by_violations',
            field=models.BooleanField(default=False, verbose_name='Qoidabuzarliklar sababli bloklangan'),
        ),
    ]
