# Generated by Django 4.2 on 2026-08-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_is_blocked_by_violations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='assessment_qualified',
            new_name='assessment_qualified_status',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='practice_qualified',
            new_name='practice_qualified_status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assessment_qualified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bilim baholashdan o'tgan sana"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='practice_qualified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Amaliyotdan o'tgan sana"),
        ),
    ]
