# Generated by Django 4.2 on 2026-05-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_photo_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('organization_leader', 'Tashkilot rahbari'), ('department_admin', 'Boshqarma admini'), ('section_admin', 'Bo‘lim admini'), ('worker', 'Xodim')], max_length=32),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='foydalanuvchi',
        ),
    ]
