# Generated by Django 4.2 on 2026-09-24 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_userprofile_otp_code_userprofile_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved_by_dept_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshqarma qabul qilgan sana'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by_dept_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_department_workers', to=settings.AUTH_USER_MODEL, verbose_name="Qabul qilgan boshqarma boshlig'i"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Faol ishlamoqda'), ('on_leave', 'Ta‘tilda (O‘z hisobidan / Mehnat ta‘tili)'), ('dismissed', 'Ishdan bo‘shatilgan'), ('blocked', 'Bloklangan')], default='active', max_length=20, verbose_name='Mehnat holati'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved_by_dept',
            field=models.BooleanField(default=False, verbose_name='Boshqarma tomonidan qabul qilingan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='one_id_user_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='One ID identifikatori'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Pasport raqami'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_series',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Pasport seriyasi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='JShShIR (PINFL)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Holat o‘zgargan sana'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Holatni o‘zgartirgan rahbar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_reason',
            field=models.TextField(blank=True, default='', verbose_name='Holat sababi / Izoh'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='type',
            field=models.CharField(choices=[('guideline', "Yo'riqnoma"), ('test', 'Test va baholash'), ('practice', 'Ish amaliyoti'), ('violation', 'Qoidabuzarlik'), ('permission', 'Mehnatga ruxsat'), ('system', 'Tizim xabari')], default='system', max_length=20),
        ),
    ]
