# Generated by Django 4.2 on 2026-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_approved_by_dept_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('organization_leader', 'Tashkilot rahbari'), ('department_admin', 'Boshqarma admini'), ('section_admin', 'Bo‘lim admini'), ('worker', 'Xodim'), ('inspection', 'Mehnat inspeksiyasi')], max_length=32),
        ),
    ]
