# Generated by Django 4.2 on 2026-05-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_create_20_workers_default_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='practice_qualified',
            field=models.BooleanField(default=False, verbose_name="Amaliyotdan o'tgan (ishlashga yaroqli)"),
        ),
    ]
