# Generated by Django 4.2 on 2026-05-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_practice_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assessment_qualified',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name="Bilim baholashdan o'tgan (None=sinalmagan, True=o'tdi, False=o'tmadi)"),
        ),
    ]
