# Generated by Django 4.2 on 2026-06-08 16:08

from django.db import migrations, models
import django.db.models.deletion


def backfill_userprofile_organization(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    leaders = {}

    for leader in UserProfile.objects.filter(role='organization_leader').order_by('id'):
        org_name = (leader.organization_name or '').strip()
        if org_name and org_name not in leaders:
            leaders[org_name] = leader
        leader.organization_id = leader.id
        leader.save(update_fields=['organization'])

    for profile in UserProfile.objects.exclude(role='organization_leader'):
        org_name = (profile.organization_name or '').strip()
        leader = leaders.get(org_name)
        if leader:
            profile.organization_id = leader.id
            if not profile.industry_id:
                profile.industry_id = leader.industry_id
                profile.save(update_fields=['organization', 'industry'])
            else:
                profile.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_assessment_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'organization_leader'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_members', to='accounts.userprofile', verbose_name='Tashkilot'),
        ),
        migrations.RunPython(backfill_userprofile_organization, migrations.RunPython.noop),
    ]
