# Generated by Django 4.2 on 2026-09-26 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu / Tekshiruv predmeti')),
                ('notes', models.TextField(verbose_name="Ko'rsatma / Qayd / Kamchiliklar")),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Bartaraf etilgan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_notes', to=settings.AUTH_USER_MODEL, verbose_name='Inspektor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_notes', to='accounts.userprofile', verbose_name='Tashkilot rahbari / Korxona')),
            ],
            options={
                'verbose_name': 'Inspeksiya qaydi',
                'verbose_name_plural': 'Inspeksiya qaydlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
