# Generated by Django 4.2 on 2026-06-24 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.userprofile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_departments', to=settings.AUTH_USER_MODEL, verbose_name='Boshqarma nazoratchisi')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'boshqarma',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('duration', models.PositiveIntegerField(verbose_name='Davomiyligi (daqiqa)')),
                ('questions_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('attempts_allowed', models.PositiveIntegerField(default=1, verbose_name='Urinishlar soni')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('is_published', models.BooleanField(default=False, verbose_name='Joriy qilingan')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='companies.department', verbose_name='Boshqarma')),
            ],
            options={
                'verbose_name_plural': 'Department assessments',
                'db_table': 'boshqarma_baholash',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='companies.departmentassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boshqarma_baholash_urinish',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='entry_guidelines/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entry_guidelines', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_guidelines', to='companies.department')),
            ],
            options={
                'verbose_name_plural': 'Entry guidelines',
                'db_table': 'kirish_nizom',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='companies.entryguideline')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_guideline_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guideline dispatches',
                'db_table': 'nizom_yuborish',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='companies.department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sections', to=settings.AUTH_USER_MODEL, verbose_name='Bo‘lim nazoratchisi')),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'db_table': 'bolim',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectionInternalGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='section_internal_guidelines/')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('registration_end_time', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tish oxiri")),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Faollik tugashi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_section_internal_guidelines', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_guidelines', to='companies.section')),
            ],
            options={
                'verbose_name_plural': 'Section internal guidelines',
                'db_table': 'ichki_nizom',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionInternalGuidelineDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('registration_end_time', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tish oxiri")),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Faollik tugashi')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='companies.sectioninternalguideline')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_section_internal_guideline_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Section internal guideline dispatches',
                'db_table': 'ichki_nizom_yuborish',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='companies.section')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_section_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Section messages',
                'db_table': 'xabar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionWorkPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_work_practices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_practices', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_work_practices', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_practices', to='companies.section')),
            ],
            options={
                'verbose_name_plural': 'Section work practices',
                'db_table': 'ish_amaliyot',
                'ordering': ['-start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionWorkPracticeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_messages', to='companies.sectionworkpractice')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_work_practice_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work practice messages',
                'db_table': 'amaliyot_xabar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPracticeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('duration', models.PositiveIntegerField(verbose_name='Davomiyligi (daqiqa)')),
                ('attempts_allowed', models.PositiveIntegerField(verbose_name='Urinishlar soni')),
                ('questions_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_tests', to='companies.section')),
            ],
            options={
                'verbose_name_plural': 'Work practice tests',
                'db_table': 'amaliyot_test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPracticeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='companies.sectionworkpractice')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='companies.workpracticetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work practice test attempts',
                'db_table': 'amaliyot_test_urinish',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPracticeTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_1', models.CharField(max_length=255, verbose_name='1-variant')),
                ('option_2', models.CharField(max_length=255, verbose_name='2-variant')),
                ('option_3', models.CharField(max_length=255, verbose_name='3-variant')),
                ('correct_option', models.IntegerField(choices=[(1, '1-variant'), (2, '2-variant'), (3, '3-variant')], verbose_name="To'g'ri variant")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.workpracticetest')),
            ],
            options={
                'verbose_name_plural': 'Work practice test questions',
                'db_table': 'amaliyot_test_savol',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionWorkPracticeMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='companies.sectionworkpracticemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_practice_message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work practice message receipts',
                'db_table': 'amaliyot_xabar_holat',
            },
        ),
        migrations.CreateModel(
            name='SectionWorkPracticeAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='companies.sectionworkpractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_practice_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Section work practice assignees',
                'db_table': 'ish_amaliyot_azo',
            },
        ),
        migrations.CreateModel(
            name='SectionMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='companies.sectionmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Section message receipts',
                'db_table': 'xabar_holat',
            },
        ),
        migrations.CreateModel(
            name='SectionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Section memberships',
                'db_table': 'azo',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionInternalGuidelineRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='companies.sectioninternalguidelinedispatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_internal_guideline_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Section internal guideline recipients',
                'db_table': 'ichki_nizom_qabul',
                'ordering': ['user__profile__full_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineDispatchRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_kind', models.CharField(choices=[('section', 'Bo‘lim'), ('worker', 'Xodim')], max_length=16)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='companies.guidelinedispatch')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guideline_recipients', to='companies.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideline_dispatch_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guideline dispatch recipients',
                'db_table': 'nizom_qabul',
                'ordering': ['section__name', 'user__profile__full_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_1', models.CharField(max_length=500, verbose_name='A variant')),
                ('option_2', models.CharField(max_length=500, verbose_name='B variant')),
                ('option_3', models.CharField(max_length=500, verbose_name='C variant')),
                ('correct_option', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], verbose_name="To'g'ri variant")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.departmentassessment')),
            ],
            options={
                'db_table': 'boshqarma_baholash_savol',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.departmentassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_assessment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boshqarma_baholash_xabar',
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_answers', to='companies.departmentassessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.departmentassessmentquestion')),
            ],
            options={
                'db_table': 'boshqarma_baholash_javob',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='industries.industry')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'tashkilot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPracticeTestPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_permissions', to='companies.sectionworkpractice')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_permissions', to='companies.workpracticetest')),
            ],
            options={
                'verbose_name_plural': 'Work practice test permissions',
                'db_table': 'amaliyot_test_ruxsat',
                'unique_together': {('test', 'practice')},
            },
        ),
        migrations.CreateModel(
            name='WorkPracticeTestAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='companies.workpracticetestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.workpracticetestquestion')),
            ],
            options={
                'db_table': 'amaliyot_test_javob',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AddConstraint(
            model_name='sectionworkpracticemessagereceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_work_practice_message_recipient'),
        ),
        migrations.AddConstraint(
            model_name='sectionworkpracticeassignee',
            constraint=models.UniqueConstraint(fields=('practice', 'user'), name='unique_work_practice_assignee'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionmessagereceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AddConstraint(
            model_name='sectionmembership',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_section_member_per_user'),
        ),
        migrations.AddConstraint(
            model_name='sectioninternalguidelinerecipient',
            constraint=models.UniqueConstraint(fields=('dispatch', 'user'), name='unique_section_internal_guideline_recipient_per_dispatch'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'name')},
        ),
        migrations.AddConstraint(
            model_name='guidelinedispatchrecipient',
            constraint=models.UniqueConstraint(fields=('dispatch', 'user'), name='unique_guideline_recipient_per_dispatch'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentassessmentnotification',
            unique_together={('assessment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentassessmentattemptanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('leader', 'name')},
        ),
    ]
