# Generated by Django 4.2 on 2026-05-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_workers'),
        ('companies', '0002_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('leader', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='companies.department')),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'ordering': ['name'],
                'unique_together': {('department', 'name')},
            },
        ),
    ]
