# Generated by Django 4.2 on 2026-07-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
        ('companies', '0003_work_practice_assignee_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmembership',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_memberships', to='professions.profession', verbose_name='Kasb'),
        ),
    ]
