# Generated by Django 4.2 on 2026-07-08 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_sectionmembership_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline_type', models.CharField(choices=[('medical', 'Tibbiy yordam yo‘riqnomasi'), ('fire', "Yong'in xavfsizligi yo‘riqnomasi"), ('electric', 'Elektr xavfsizligi yo‘riqnomasi')], max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='mandatory_guidelines/')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('active_until', models.DateTimeField(verbose_name='Faollik tugashi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mandatory_guidelines', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_guidelines', to='companies.department')),
            ],
            options={
                'db_table': 'majburiy_yoriqnoma',
                'ordering': ['guideline_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionGuidelineReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profession_guideline_receipt', to='companies.sectionmembership')),
            ],
            options={
                'db_table': 'kasb_yoriqnoma_qabul',
            },
        ),
        migrations.CreateModel(
            name='MandatoryGuidelineReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='companies.mandatoryguideline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_guideline_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'majburiy_yoriqnoma_qabul',
                'ordering': ['guideline__guideline_type', 'user__profile__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='mandatoryguidelinereceipt',
            constraint=models.UniqueConstraint(fields=('guideline', 'user'), name='unique_mandatory_guideline_receipt'),
        ),
        migrations.AlterUniqueTogether(
            name='mandatoryguideline',
            unique_together={('department', 'guideline_type')},
        ),
    ]
