# Generated by Django 4.2 on 2026-07-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
        ('companies', '0005_mandatoryguideline_professionguidelinereceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionguidelinereceipt',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guideline_receipts', to='professions.profession'),
        ),
    ]
