# Generated by Django 4.2 on 2026-07-09 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professions', '0001_initial'),
        ('companies', '0006_professionguidelinereceipt_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Boshlanish sana')),
                ('end_date', models.DateField(verbose_name='Tugash sana')),
                ('file', models.FileField(blank=True, null=True, upload_to='medical_records/', verbose_name='Fayl')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='companies.department', verbose_name='Boshqarma')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='professions.profession', verbose_name='Kasb')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='companies.section', verbose_name="Bo'lim")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'db_table': 'tibbiy_malumot',
                'ordering': ['end_date', 'user__profile__full_name'],
            },
        ),
    ]
