# Generated by Django 4.2 on 2026-07-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_employeemedicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTestBaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_1', models.CharField(max_length=500, verbose_name='A variant')),
                ('option_2', models.CharField(max_length=500, verbose_name='B variant')),
                ('option_3', models.CharField(max_length=500, verbose_name='C variant')),
                ('correct_option', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], verbose_name="To'g'ri variant")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_base_questions', to='companies.department')),
            ],
            options={
                'db_table': 'boshqarma_test_bazasi_savol',
                'ordering': ['-created_at'],
            },
        ),
    ]
