# Generated by Django 4.2 on 2026-08-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_departmenttestbasequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
