# Generated by Django 4.2 on 2026-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_password_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
