# Generated by Django 4.2 on 2026-08-06 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_rename_assessment_qualified_userprofile_assessment_qualified_status_and_more'),
        ('companies', '0010_company_is_password_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('from_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='companies.section')),
                ('to_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='companies.section')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transfers', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='accounts.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Worker transfer histories',
                'db_table': 'worker_transfer_history',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
