# Generated by Django 4.2 on 2026-05-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_section_work_practices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='tashkilot',
        ),
        migrations.AlterModelTable(
            name='department',
            table='boshqarma',
        ),
        migrations.AlterModelTable(
            name='entryguideline',
            table='kirish_nizom',
        ),
        migrations.AlterModelTable(
            name='guidelinedispatch',
            table='nizom_yuborish',
        ),
        migrations.AlterModelTable(
            name='guidelinedispatchrecipient',
            table='nizom_qabul',
        ),
        migrations.AlterModelTable(
            name='section',
            table='bolim',
        ),
        migrations.AlterModelTable(
            name='sectioninternalguideline',
            table='ichki_nizom',
        ),
        migrations.AlterModelTable(
            name='sectioninternalguidelinedispatch',
            table='ichki_nizom_yuborish',
        ),
        migrations.AlterModelTable(
            name='sectioninternalguidelinerecipient',
            table='ichki_nizom_qabul',
        ),
        migrations.AlterModelTable(
            name='sectionmembership',
            table='azo',
        ),
        migrations.AlterModelTable(
            name='sectionmessage',
            table='xabar',
        ),
        migrations.AlterModelTable(
            name='sectionmessagereceipt',
            table='xabar_holat',
        ),
        migrations.AlterModelTable(
            name='sectionworkpractice',
            table='ish_amaliyot',
        ),
        migrations.AlterModelTable(
            name='sectionworkpracticeassignee',
            table='ish_amaliyot_azo',
        ),
    ]
