# Generated by Django 4.2 on 2026-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_workertransferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryguideline',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Faollik tugashi'),
        ),
        migrations.AddField(
            model_name='entryguideline',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Faollik boshlanishi'),
        ),
    ]
