# Generated by Django 4.2 on 2026-05-30 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0012_alter_company_table_alter_department_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionworkpractice',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionworkpractice',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_work_practices', to=settings.AUTH_USER_MODEL),
        ),
    ]
