# Generated by Django 4.2 on 2026-08-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_entryguideline_active_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryguideline',
            name='active_until',
        ),
        migrations.RemoveField(
            model_name='entryguideline',
            name='start_time',
        ),
    ]
