# Generated by Django 4.2 on 2026-08-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_remove_entryguideline_active_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sertifikat turi nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_certificate_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Certificate Types',
                'db_table': 'sertifikat_turi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/', verbose_name='Sertifikat (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_certificates', to='companies.certificatetype', verbose_name='Sertifikat turi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
            ],
            options={
                'verbose_name_plural': 'Employee Certificates',
                'db_table': 'xodim_sertifikati',
                'ordering': ['-created_at'],
            },
        ),
    ]
