# Generated by Django 4.2 on 2026-05-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_sectionworkpractice_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionworkpractice',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_work_practices', to=settings.AUTH_USER_MODEL),
        ),
    ]
