# Generated by Django 4.2 on 2026-05-30 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0014_sectionworkpractice_responsible_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionWorkPracticeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_messages', to='companies.sectionworkpractice')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_work_practice_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work practice messages',
                'db_table': 'amaliyot_xabar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionWorkPracticeMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='companies.sectionworkpracticemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_practice_message_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work practice message receipts',
                'db_table': 'amaliyot_xabar_holat',
            },
        ),
        migrations.AddConstraint(
            model_name='sectionworkpracticemessagereceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_work_practice_message_recipient'),
        ),
    ]
