# Generated by Django 4.2 on 2026-08-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_certificatetype_employeecertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmembership',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.section'),
        ),
    ]
