# Generated by Django 4.2 on 2026-05-31 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0015_sectionworkpracticemessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPracticeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('duration', models.PositiveIntegerField(verbose_name='Davomiyligi (daqiqa)')),
                ('attempts_allowed', models.PositiveIntegerField(verbose_name='Urinishlar soni')),
                ('questions_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_tests', to='companies.section')),
            ],
            options={
                'verbose_name_plural': 'Work practice tests',
                'db_table': 'amaliyot_test',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPracticeTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_1', models.CharField(max_length=255, verbose_name='1-variant')),
                ('option_2', models.CharField(max_length=255, verbose_name='2-variant')),
                ('option_3', models.CharField(max_length=255, verbose_name='3-variant')),
                ('correct_option', models.IntegerField(choices=[(1, '1-variant'), (2, '2-variant'), (3, '3-variant')], verbose_name="To'g'ri variant")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.workpracticetest')),
            ],
            options={
                'verbose_name_plural': 'Work practice test questions',
                'db_table': 'amaliyot_test_savol',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPracticeTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='companies.sectionworkpractice')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='companies.workpracticetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work practice test attempts',
                'db_table': 'amaliyot_test_urinish',
                'ordering': ['-started_at'],
            },
        ),
    ]
