# Generated by Django 4.2 on 2026-09-09 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0015_alter_sectionmembership_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentassessment',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name="Oldindan to'xtatilgan"),
        ),
        migrations.AddField(
            model_name='departmentassessment',
            name='stop_reason',
            field=models.TextField(blank=True, verbose_name="To'xtatish sababi / Izoh"),
        ),
        migrations.AddField(
            model_name='departmentassessment',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan sana"),
        ),
        migrations.AddField(
            model_name='departmentassessment',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_assessments', to=settings.AUTH_USER_MODEL, verbose_name="To'xtatgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='guidelinedispatch',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name="Oldindan to'xtatilgan"),
        ),
        migrations.AddField(
            model_name='guidelinedispatch',
            name='stop_reason',
            field=models.TextField(blank=True, verbose_name="To'xtatish sababi / Izoh"),
        ),
        migrations.AddField(
            model_name='guidelinedispatch',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan sana"),
        ),
        migrations.AddField(
            model_name='guidelinedispatch',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_guideline_dispatches', to=settings.AUTH_USER_MODEL, verbose_name="To'xtatgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='mandatoryguideline',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name="Oldindan to'xtatilgan"),
        ),
        migrations.AddField(
            model_name='mandatoryguideline',
            name='stop_reason',
            field=models.TextField(blank=True, verbose_name="To'xtatish sababi / Izoh"),
        ),
        migrations.AddField(
            model_name='mandatoryguideline',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan sana"),
        ),
        migrations.AddField(
            model_name='mandatoryguideline',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_mandatory_guidelines', to=settings.AUTH_USER_MODEL, verbose_name="To'xtatgan foydalanuvchi"),
        ),
    ]
