# Generated by Django 4.2 on 2026-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_departmentassessment_is_stopped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentassessment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='departmentassessment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
