# Generated by Django 4.2 on 2026-05-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_workpracticetest_workpracticetestquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPracticeTestPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_permissions', to='companies.sectionworkpractice')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_permissions', to='companies.workpracticetest')),
            ],
            options={
                'verbose_name_plural': 'Work practice test permissions',
                'db_table': 'amaliyot_test_ruxsat',
                'unique_together': {('test', 'practice')},
            },
        ),
    ]
