# Generated by Django 4.2 on 2026-05-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_add_workpracticetestpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPracticeTestAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='companies.workpracticetestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.workpracticetestquestion')),
            ],
            options={
                'db_table': 'amaliyot_test_javob',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
