# Generated by Django 4.2 on 2026-09-09 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0017_departmentassessment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name="To'xtatilganmi"),
        ),
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='stop_reason',
            field=models.TextField(blank=True, default='', verbose_name="To'xtatish sababi"),
        ),
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan vaqti"),
        ),
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_section_internal_guidelines', to=settings.AUTH_USER_MODEL, verbose_name="To'xtatgan shaxs"),
        ),
        migrations.AddField(
            model_name='workpracticetest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='workpracticetest',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name="To'xtatilganmi"),
        ),
        migrations.AddField(
            model_name='workpracticetest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='workpracticetest',
            name='stop_reason',
            field=models.TextField(blank=True, default='', verbose_name="To'xtatish sababi"),
        ),
        migrations.AddField(
            model_name='workpracticetest',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'xtatilgan vaqti"),
        ),
        migrations.AddField(
            model_name='workpracticetest',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_work_practice_tests', to=settings.AUTH_USER_MODEL, verbose_name="To'xtatgan shaxs"),
        ),
    ]
