# Generated by Django 4.2 on 2026-09-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_sectioninternalguidelinedispatch_is_stopped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentassessment',
            name='target_sections',
            field=models.ManyToManyField(blank=True, related_name='targeted_department_assessments', to='companies.section', verbose_name="Joriy qilingan bo'limlar"),
        ),
    ]
