# Generated by Django 4.2 on 2026-05-31 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0018_add_attemptanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test nomi')),
                ('duration', models.PositiveIntegerField(verbose_name='Davomiyligi (daqiqa)')),
                ('questions_count', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('attempts_allowed', models.PositiveIntegerField(default=1, verbose_name='Urinishlar soni')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('is_published', models.BooleanField(default=False, verbose_name='Joriy qilingan')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='companies.department', verbose_name='Boshqarma')),
            ],
            options={
                'verbose_name_plural': 'Department assessments',
                'db_table': 'boshqarma_baholash',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='companies.departmentassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boshqarma_baholash_urinish',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_1', models.CharField(max_length=500, verbose_name='A variant')),
                ('option_2', models.CharField(max_length=500, verbose_name='B variant')),
                ('option_3', models.CharField(max_length=500, verbose_name='C variant')),
                ('correct_option', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], verbose_name="To'g'ri variant")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.departmentassessment')),
            ],
            options={
                'db_table': 'boshqarma_baholash_savol',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.departmentassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_assessment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boshqarma_baholash_xabar',
                'unique_together': {('assessment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentAssessmentAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_answers', to='companies.departmentassessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.departmentassessmentquestion')),
            ],
            options={
                'db_table': 'boshqarma_baholash_javob',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
