# Generated by Django 4.2 on 2026-06-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_add_department_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidelinedispatch',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guidelinedispatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
