# Generated by Django 4.2 on 2026-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_departmentassessment_target_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionworkpractice',
            name='responsible_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectionworkpractice',
            name='responsible_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionworkpracticeassignee',
            name='trainee_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectionworkpracticeassignee',
            name='trainee_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
