# Generated by Django 4.2 on 2026-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_sectionworkpractice_responsible_accepted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mandatoryguideline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mandatoryguideline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Joriy faol'),
        ),
    ]
