# Generated by Django 4.2 on 2026-06-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_guidelinedispatch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sectioninternalguidelinedispatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
