# Generated by Django 4.2 on 2026-09-26 11:46

import django.core.validators
from django.db import migrations, models


def keep_legacy_threshold(apps, schema_editor):
    # Mavjud testlar avval qat'iy 60% chegarasi bilan baholangan - natijalar o'zgarmasligi uchun saqlanadi.
    WorkPracticeTest = apps.get_model('companies', 'WorkPracticeTest')
    WorkPracticeTest.objects.update(pass_percentage=60)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_alter_mandatoryguideline_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpracticetest',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name="O'tish bali (%)"),
        ),
        migrations.AddField(
            model_name='workpracticetestattempt',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(keep_legacy_threshold, migrations.RunPython.noop),
    ]
