# Generated by Django 4.2 on 2026-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_sectioninternalguidelinedispatch_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninternalguidelinedispatch',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
    ]
