# Generated by Django 4.2 on 2026-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_alter_sectioninternalguidelinedispatch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninternalguideline',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Faollik tugashi'),
        ),
        migrations.AddField(
            model_name='sectioninternalguideline',
            name='registration_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tish oxiri"),
        ),
        migrations.AddField(
            model_name='sectioninternalguideline',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Faollik tugashi'),
        ),
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='registration_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tish oxiri"),
        ),
        migrations.AddField(
            model_name='sectioninternalguidelinedispatch',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
