# Generated by Django 4.2 on 2026-06-24 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import professions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nizom_file', models.FileField(blank=True, null=True, upload_to='nizom_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx']), professions.models.validate_file_size_20mb])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='industries.industry')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'industry')},
            },
        ),
    ]
