# Generated by Django 4.2 on 2026-08-06 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0001_initial'),
        ('accounts', '0006_userprofile_is_blocked_by_violations'),
        ('companies', '0008_departmenttestbasequestion'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profession',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_professions', to='companies.department'),
        ),
        migrations.AddField(
            model_name='profession',
            name='organization',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'organization_leader'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_professions', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='industries.industry'),
        ),
    ]
