# Generated by Django 6.0.3 on 2026-03-24 09:06

import django.core.validators
import professions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='nizom_file',
            field=models.FileField(blank=True, null=True, upload_to='nizom_files/', validators=[django.core.validators.FileExtensionValidator(['pdf']), professions.models.validate_file_size_1mb]),
        ),
    ]
