# Generated by Django 4.2 on 2026-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_alter_profession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
