# Generated by Django 4.2 on 2026-08-04 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Qoidabuzarlik turi nomi')),
            ],
            options={
                'verbose_name': 'Qoidabuzarlik turi',
                'verbose_name_plural': 'Qoidabuzarlik turlari',
                'db_table': 'qoidabuzarlik_turi',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Sabab (Izoh)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi (Tushuntirish xati olinmagan)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_violations', to=settings.AUTH_USER_MODEL, verbose_name='Kiritgan nazoratchi')),
                ('violation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.violationtype', verbose_name='Qoidabuzarlik turi')),
            ],
            options={
                'verbose_name': 'Qoidabuzarlik',
                'verbose_name_plural': 'Qoidabuzarliklar',
                'db_table': 'qoidabuzarlik',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExplanationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_text', models.TextField(verbose_name='Izoh (Tushuntirish)')),
                ('file', models.FileField(upload_to='explanation_letters/', verbose_name='Tushuntirish xati (PDF/Rasm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_letters', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('unblocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocked_employees', to=settings.AUTH_USER_MODEL, verbose_name='Blokdan chiqargan shaxs')),
            ],
            options={
                'verbose_name': 'Tushuntirish xati',
                'verbose_name_plural': 'Tushuntirish xatlari',
                'db_table': 'tushuntirish_xati',
                'ordering': ['-created_at'],
            },
        ),
    ]
