# Generated by Django 4.2 on 2026-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/', verbose_name='Qoidabuzarlik rasmi'),
        ),
    ]
