# Generated by Django 4.2 on 2026-09-24 08:57

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_violation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationletter',
            name='file',
            field=models.FileField(upload_to='explanation_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'webp']), core.validators.validate_file_security], verbose_name='Tushuntirish xati (PDF/Rasm)'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_file_security], verbose_name='Qoidabuzarlik rasmi'),
        ),
    ]
